### PR TITLE
Adapt dialog template to Bootstrap styles

### PR DESCRIPTION
**Pull request by adpe**
Hey @dthies 

I've updated the UI to Bootstrap styles (in a way it was possible, without big refactoring). Furthermore, I've made some little CSS changes.

Hope you're happy with it.

Greets
Adrian

### CODE REVIEW

**Comment by adpe** [comment]
I've found a bug. If you delete the only possible answer, and want to add a new one, it will fail.

**Comment by adpe** [comment]
I was working on it and fixed one regression. Furthermore, I added support for GH actions, as my free plan on Travis is already exceeded.

**Comment by dthies** [comment]
Thank you very much Adrien. This looks really great. I had started on this several times and never had time to finish. Your lay looks much better. Thank also for the Github actions support.

**Comment by adpe** [comment]
Thanks @dthies 

I've tested it out on 2 devices (Win 10 Chrome/macOS Safari) and it looks better as the old way. Hopefully it will not lead to many problems, but I don't think so. In general, I didn't change the logic, so it should be safe.

Greets
Adrian

**Comment by dthies** [comment]
It occurred to me when thinking of updating the database that we would be using Bootstrap 4. There could be problems with older themes. I changed the maturity to beta in the version file which should be give a warning before admins try to install it on a production system. 
When this is copied to the plugins database I will specify only current Moodle versions so only updated systems can install it. We need to change the strings to use values in the plugins lang file rather then use existing strings. So this is due for a major upgrade anyway.

**Pull request merged**
